version: '3'

services:
  fastapi-app:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: migrationdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  postgres_db:
    driver: local
  fastapi_app_data:
    driver: local